from distutils.core import setup

setup(name='lookit',
      version='1.1.0',
      description='Quick Screenshot Uploader',
      author='Zach Tibbitts',
      author_email='zachtib@gmail.com',
      url='http://zachtib.github.com/lookit',
      license='GPLv3',
      packages=['lookit'],
      package_dir={'lookit': 'src'},
      package_data={'lookit': ['data/*.xml', 'poster/*.py']},
      scripts=['src/lookit'],
      data_files=[('share/applications', ['lookit.desktop']),
		  ('share/pixmaps', ['lookit.svg', 'lookit-dark.svg', 
						'lookit-light.svg']),
          ('share/gnome-shell/extensions/lookit@extensions.zachtib.com',
          ['src/gnome-shell/extensions/lookit@extensions.zachtib.com/extension.js',
           'src/gnome-shell/extensions/lookit@extensions.zachtib.com/metadata.json',
           'src/gnome-shell/extensions/lookit@extensions.zachtib.com/stylesheet.css'])],
     )
